FROM python:2-alpine

RUN \
    apk --no-cache add openldap-dev && \
    apk --no-cache add --virtual build-dependencies build-base && \
    pip install python-ldap && \
    apk del build-dependencies

COPY nginx-ldap-auth-daemon.py /

EXPOSE 8888

CMD ["python", "/nginx-ldap-auth-daemon.py"]